@startuml Diagrama secuencia jugar mano y pierde
    actor Interfaz
    participant ":Juego" as Juego
    participant "rondaActual:Ronda" as RondaActual
    
    Interfaz -> Juego: jugarMano(cartas,mano)

    activate Juego

    Juego --> Interfaz: puntajeFinal

    deactivate Juego

    Interfaz -> Juego: avanzarTurno()

    activate Juego

    Juego -> Juego: getRondaActual()

    activate Juego
    deactivate Juego

    Juego -> RondaActual: seAlcanzoElPuntajeDeRonda()

    activate RondaActual

    RondaActual --> Juego: true

    deactivate RondaActual

    Juego --> Interfaz: false

    deactivate Juego

    Interfaz -> Juego: avanzarRonda()

    activate Juego

    Juego -> Juego: getRondaActual()

    activate Juego
    deactivate Juego

    Juego -> RondaActual: seAlcanzoElPuntajeDeRonda()

    activate RondaActual

    RondaActual --> Juego: true

    deactivate RondaActual

    Juego -> Juego: esUltimaRonda()

    activate Juego
    deactivate Juego

    Juego --> Interfaz: false

    deactivate Juego

    Interfaz -> Juego: seGanoPartida()

    activate Juego

    Juego --> Interfaz: true

    deactivate Juego

@enduml