@startuml Diagrama secuencia aplicarEfecto Comodin Regular
    participant ":Turno" as Turno
    participant "comodin:ComodinRegular" as Comodin
    participant "estrategia:EstrategiaSumarMultiplicar" as EstrategiaComodin
    participant "mano:Mano" as Mano 

    Turno -> Comodin: aplicarEfecto(mano)

    activate Comodin
    
    Comodin -> EstrategiaComodin: realizarModificacion(puntos,multiplicador,mano)
    
    activate EstrategiaComodin

    EstrategiaComodin -> Mano: aumentarYMultiplicar(puntos,multiplicador)

    activate Mano
    deactivate Mano
    deactivate EstrategiaComodin
    deactivate Comodin

@enduml